/*
 * Auto & General test API
 * This is an example implementation of API for testing candidates  - You DON'T need to implement `/integrationTest` and `/status` endpoints - You can run automated integration tests against your API using `/integrationTest` endpoint
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package au.com.autogeneral.join.angapi.tasks.model;

import io.swagger.annotations.ApiModelProperty;
import lombok.AllArgsConstructor;
import lombok.Value;
import lombok.experimental.FieldDefaults;

@Value
@FieldDefaults(makeFinal = false)
@AllArgsConstructor
public class BalanceTestResult {
    
    @ApiModelProperty(example = "[(]", value = "")
    private String input = null;

    @ApiModelProperty(example = "false", value = "")
    private Boolean isBalanced = null;

}
